name: Build all Targets
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test
        run: ./gradlew allTests
      - name: Build jar
        run: ./gradlew assemble
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: multibase
          path: |
            build/libs/*jar
            build/libs/*klib
